bufbuild/rules_buf

buf/defs.bzl
This silences warnings from bazel like:
```
Test execution time (0.4s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
```
=> Mark lint and breaking tests as timeout short by default

buf/internal/toolchain.bzl
We add a `sha256` argument to `rules_buf_toolchains` which allows for setting a `sha256` value for the released `sha256.txt` file. This is necessary in environments like Stripe where we do not allow _any_ external dependencies that don't specify a SHA-256 in order to have fully deterministic external inputs. I've tested each combination of the inputs below.
With neither `version` nor `sha256`:
```
$ bazel build //...
DEBUG: Rule 'rules_buf_toolchains' indicated that a canonical reproducible form can be obtained by modifying arguments version = "v1.16.0", sha256 = "d1324e435706422aaf639815fd82724599cc03a432d6cf9865c6fe47e2c94fe9"
DEBUG: Repository rules_buf_toolchains instantiated at:
/Users/sushain/stripe/rules_buf/examples/workspace/WORKSPACE:10:21: in <toplevel> …
```
=> Support fully deterministic toolchain

buf/internal/toolchain.bzl
Closes #39 
Allow configuring a mirror for `buf` binary downloads
=> Add repository_url option for buf dowloads to allow mirroring

MODULE.bazel, buf/extensions.bzl, buf/internal/toolchain.bzl, examples/bzlmod/.bazelrc, examples/bzlmod/BUILD.bazel, examples/bzlmod/MODULE.bazel, examples/bzlmod/WORKSPACE, examples/bzlmod/buf.yaml, examples/bzlmod/file.proto, examples/bzlmod/unused.proto
Bazel modules are moving away from setup in WORKSPACE files, towards a 'package manager' called bzlmod. Such modules are published on https://registry.bazel.build and are easier for developers to consume in their Bazel projects.
=> Add bzlmod support

buf/internal/breaking.bzl, buf/internal/lint.bzl, examples/single_module/BUILD.bazel, examples/single_module/bar/v1/BUILD.bazel, examples/single_module/foo/v1/BUILD.bazel
Add support for `--error-format` of `buf breaking` and `buf lint`. Closes #19
=> Support `--error-format`

MODULE.bazel, buf/BUILD.bazel, buf/extensions.bzl, examples/bzlmod/BUILD.bazel, examples/bzlmod/MODULE.bazel
Support gazelle in bzlmod. #42 added support for bzlmod but it did not support the gazelle plugin, this updates the module file to support gazelle.
=> Support gazelle in bzlmod

MODULE.bazel, buf/defs.bzl
Release prep `v0.2.0`. Hides the unreleased `buf_push` rule. It can once we address https://github.com/bufbuild/rules_buf/issues/43
=> Release prep `v0.2.0`

buf/internal/breaking.bzl, buf/internal/lint.bzl, buf/internal/plugin.bzl
Closes https://github.com/bufbuild/rules_buf/issues/37
=> Add `protoc_args` attribute to `buf_lint_test` and `buf_breaking_test`

buf/extensions.bzl
I started to use rules_rust, which uses rules_buf.
I also use bzlmod and download all dependencies ahead of time to support builds without internet access.
For this to work, all downloads from the internet need to provide sha256 hash in the download actions. I saw that for the WORKSPACE style usage, this already works (`buf_download_releases` already supports that).
This MR adds the correct hash for v1.28.1 and allows to also override the hash in addition to the version.
=> Add sha256 support for bzlmod case

MODULE.bazel
* Add `protoc_args` attribute to `buf_lint_test` and `buf_breaking_test` by @sushain97 in https://github.com/bufbuild/rules_buf/pull/50
* Get the os info from repo ctx by @kusaeva in https://github.com/bufbuild/rules_buf/pull/58
* Add sha256 support for bzlmod case by @adrianimboden in https://github.com/bufbuild/rules_buf/pull/61
* Add `module` option to `lint` and `breaking` rules by @srikrsna-buf in https://github.com/bufbuild/rules_buf/pull/65
* Add gazelle support for `v2` by @srikrsna-buf in https://github.com/bufbuild/rules_buf/pull/66
* Add support for multiple config files of different versions by @srikrsna-buf in https://github.com/bufbuild/rules_buf/pull/68
* @chrispine made their first contribution in https://github.com/bufbuild/rules_buf/pull/56
* @kusaeva made their first …
=> Release `0.3.0`

buf/internal/toolchain.bzl
From [the docs](https://bazel.build/rules/lib/builtins/repository_ctx#download): `default is ''. If set, restrict cache hits to those cases where the file was added to the cache with the same canonical id`
With `http_archive`, the default is the value of the url(s) provided, for the following reason: `This helps catch the common mistake of updating the URLs without also updating the hash, resulting in builds that succeed locally but fail on machines without the file in the cache.`
The lack of this default for `rctx.download` resulted in the exact issue described by `http_archive` to us recently. As such, this PR updates uses of `rctx.download` to mimic that behaviour to avoid this footgun.
Also addresses a ~2yr old TODO around using …
=> Use canonical_id in rctx.download and use the latest github release version

buf/internal/breaking.bzl, buf/internal/lint.bzl, buf/internal/plugin.bzl, buf/internal/toolchain.bzl
This should resolve the toolchain registration issue from #78.
Also, it adds a batch script version of the shell script shim used to invoke protoc for tests; however, this requires `--enable_runfiles` to be explicitly passed or added to `.bazelrc` for a project, as Bazel on Windows does not populate runfiles by default.
In the future, we will need a better approach to supporting Windows that uses the runfiles manifest instead. This is tricky though, and will require some careful thought.
=> Fix running tests in Windows

examples/bzlmod/MODULE.bazel
While playing around with this bazel module.
I was looking at this issue https://github.com/bufbuild/rules_buf/issues/38 
And when using the module example I wasn't able to use the bazel run cmd.
So this PR just aim to fix that.
=> Update bzlmod example to be able to use toolchain

buf/extensions.bzl
Current code has a bug, where if there are multiple registration it will not run with error: 
```
Error in sorted: unsupported comparison: dict <=> dict
```
=> Fix extensions.bzl to allow for multiple versions

MODULE.bazel, MODULE.bazel.lock
This fixes the module version, it was wrongly updated to `0.4.0`, this corrects the version back. The version has not been released on BCR so it should not create a problem
=> Fix module version

.github/workflows/tests.yaml
Bumps the actions/cache GitHub action from v2 to v4 to address the deprecation of v2: https://github.com/actions/cache/discussions/1510.
=> Bump actions/cache from v2 to v4

buf/internal/toolchain.bzl
When `repository_url` is used, bazel complains about reproducible form:
```
DEBUG: Rule 'rules_buf_toolchains' indicated that a canonical reproducible form can be obtained by dropping arguments ["repository_url"]
```
`repository_url` should be included in the attributes returned from the rule to indicate that it can also be used to generate reproducible form.
=> Add repository_url to reproducible attributes

gazelle/buf/resolve.go, gazelle/buf/testdata/breaking_module/BUILD.out, gazelle/buf/testdata/breaking_module/bar/v1/BUILD.in, gazelle/buf/testdata/breaking_module/bar/v1/BUILD.out, gazelle/buf/testdata/v2/breaking_module/BUILD.out, gazelle/buf/testdata/v2/breaking_module/bar/v1/BUILD.in, gazelle/buf/testdata/v2/breaking_module/bar/v1/BUILD.out
Updates the generation of the `buf_breaking` rule to sort the targets for stable Bazel output. Updates breaking test cases to include multiple targets.
=> Sort targets in the buf_breaking rules

MODULE.bazel, MODULE.bazel.lock
* Use canonical_id in rctx.download and use the latest github release version by @Strum355 in https://github.com/bufbuild/rules_buf/pull/62
* Fix running tests in Windows by @jchadwick-buf in https://github.com/bufbuild/rules_buf/pull/79
* Update bzlmod example to be able to use toolchain by @sfroment in https://github.com/bufbuild/rules_buf/pull/81
* Fix extensions.bzl to allow for multiple versions by @filippobrizzi in https://github.com/bufbuild/rules_buf/pull/88
* Add repository_url to reproducible attributes by @styurin in https://github.com/bufbuild/rules_buf/pull/94
* Sort targets in the buf_breaking rules by @dspencer12 in https://github.com/bufbuild/rules_buf/pull/100
* Add `buf_format` rule by @srikrsna-buf in https://github.com/bufbuild/rules_buf/pull/105
* @Strum355 made their …
=> Release `0.4.0`

.bcr/metadata.template.json, .bcr/presubmit.yml, .bcr/source.template.json
Add release templates for automating publishing to BCR. The [release process](https://github.com/bazel-contrib/publish-to-bcr/?tab=readme-ov-file#setup) was updated to use workflow, will be added as a close followup.
=> Add release templates
